version: '3.1'

services:
  server:
    container_name: pa-server
    build: .
    volumes:
      - songs:/songs
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - '8082:5000'
    depends_on:
      - db

  db:
    container_name: pa-database
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=pa-database
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8083:8080'
    depends_on:
      - db

volumes:
  pgdata:
  songs:
